# railway.toml
[build]
# Perintah untuk membangun aplikasi
buildCommand = """
cd web
bun install
bun run build
cd ..
cargo build --release
"""
# Menentukan lingkungan yang dibutuhkan
builder = "nixpacks"

[service]
# Port yang dipakai aplikasi (tetap 3000)
port = 3000

[deploy]
# Perintah untuk menjalankan aplikasi setelah selesai dibangun
startCommand = "./target/release/Mori"
